source "%val{config}/plugins/plug.kak/rc/plug.kak"

# These should be added to a separate file and sourced in.
colorscheme solarized-dark
set-option global ui_options ncurses_assistant=text
set-option global autoreload yes
set-option global tabstop 4
set-option global indentwidth 4

add-highlighter global/ number-lines -hlcursor
add-highlighter global/ show-matching
add-highlighter global/ wrap -word -indent

plug "andreyorst/powerline.kak"  defer powerline %{
    set-option global powerline-format 'mode_info bufname filetype line_column'
    powerline-toggle line_column of
    powerline-theme solarized-dark
    } config %{
    powerline-start
}

plug "gustavo-hms/luar"

plug "andreyorst/fzf.kak"
map global normal <c-p> ': fzf-mode<ret>'

plug "ul/kak-lsp" do %{
    cargo install --force --path .
} config %{
    set global lsp_diagnostic_line_error_sign '='
    set global lsp_diagnostic_line_warning_sign '|'
    set global lsp_hover_max_lines 30

    define-command ne -docstring 'go to next error/warning from lsp' %{
        lsp-find-error --include-warnings
    }

    define-command pe -docstring 'go to previous error/warning from lsp' %{
        lsp-find-error --previous --include-warnings
    }

    define-command ee -docstring 'go to current error/warning from lsp' %{
        lsp-find-error --include-warnings; lsp-find-error --previous --include-warnings
    }

    define-command lsp-restart -docstring 'restart lsp server' %{ lsp-stop; lsp-start}

	hook global WinSetOption filetype=(rust|haskell|clojure|typescript|python) %{
        set-option window lsp_auto_highlight_references true
        set-option window lsp_hover_anchor true
        echo -debug "Enabling LSP for filetype %opt{filetype}"
        lsp-enable-window
        lsp-auto-hover-enable
    }

    hook global WinSetOption filetype=(haskell) %{
        set global lsp_server_configuration pyls.configurationSources=["flake8"]
        set window lsp_server_configuration haskell.clippy_preference="text"
    }

  hook global WinSetOption filetype=(python) %{
        set global lsp_server_configuration pyls.configurationSources=["flake8"]
    }

    hook global KakEnd .* lsp-exit
}



